# -*- coding: utf-8 -*-
"""DR.Heba_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zVoqWNtaxSe1zhicU0FZ3m6A_HzSFHN4
"""

!wget "https://pynative.com/wp-content/uploads/2019/01/company_sales_data.csv"

import pandas as pd
df = pd.read_csv("/content/company_sales_data.csv")
df

"""
# **إجمالي الكمية المباعة من كل منتج خلال السنة.**


"""

import plotly.express as px
import pandas as pd


products = ["facecream", "facewash", "toothpaste", "bathingsoap", "shampoo", "moisturizer"]

totals = df[products].sum().reset_index()
totals.columns = ["product", "total_units"]

fig = px.bar(
    totals,
    x="product",
    y="total_units",
    title="Total Units Sold per Product (Yearly)",
    labels={"product":"Product", "total_units":"Total Units Sold"},
    text="total_units"
)

fig.update_traces(texttemplate='%{text:,}', textposition='outside')
fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide', yaxis_tickformat=",")
fig.show()

"""# **تغيّر مبيعات كل منتج من شهر للتاني خلال السنة.**




"""

import plotly.express as px
import pandas as pd


fig = px.line(
    df,
    x="month_number",
    y=["facecream", "facewash", "toothpaste", "bathingsoap", "shampoo", "moisturizer"],
    title="Sales Trend of Each Product Across Months",
    labels={"month_number": "Month", "value": "Units Sold", "variable": "Product"}
)

fig.update_traces(mode="lines+markers")
fig.show()

"""# **نسبة كل منتج من إجمالي المبيعات الكلية.**"""

import plotly.express as px
import pandas as pd


products = ["facecream", "facewash", "toothpaste", "bathingsoap", "shampoo", "moisturizer"]

totals = df[products].sum().reset_index()

totals.columns = ["product", "total_units"]

totals["percentage"] = totals["total_units"] / totals["total_units"].sum() * 100

fig = px.pie(
    totals,
    names="product",
    values="percentage",
    title="نسبة مساهمة كل منتج في إجمالي المبيعات (سنوي)",
    hole=0.4
)

fig.update_traces(textinfo="label+percent", textposition="inside", pull=[0.03] * len(totals))

fig.update_layout(uniformtext_minsize=10, uniformtext_mode="hide")

fig.show()

"""# **أكثر 3 شهور حققوا أعلى كمية مبيعات**"""

import pandas as pd
import plotly.express as px




top3_months = df.sort_values(by='total_units', ascending=False).head(3)

fig = px.bar(
    top3_months,
    x='total_units',
    y='month_number',
    orientation='h',
    text='total_units',
    title='Top 3 Months by Total Units Sold'
)

fig.show()

"""# **العلاقة بين عدد الوحدات المباعة وإجمالي الربح.**"""

import plotly.express as px

fig = px.scatter(
    df,
    x="total_units",
    y="total_profit",
    trendline="ols",
    trendline_color_override="red",
    title="Total Units vs Total Profit (with Trendline & Band)"
)
fig.show()

"""# **مقارنة مبيعات منتجين شهريًا على مدار السنة.**"""

import plotly.graph_objects as go
import pandas as pd

df["avg_rolling_toothpaste"] = df["toothpaste"].rolling(3).mean()
df["avg_rolling_bathingsoap"] = df["bathingsoap"].rolling(3).mean()

fig = go.Figure()

fig.add_bar(
    x=df["month_number"],
    y=df["toothpaste"],
    name="Toothpaste"
)

fig.add_bar(
    x=df["month_number"],
    y=df["bathingsoap"],
    name="Bathingsoap"
)

fig.add_trace(
    go.Scatter(
        x=df["month_number"],
        y=df["avg_rolling_toothpaste"],
        mode="lines",
        name="Toothpaste Rolling Avg",
        line=dict(dash="dot")
    )
)

fig.add_trace(
    go.Scatter(
        x=df["month_number"],
        y=df["avg_rolling_bathingsoap"],
        mode="lines",
        name="Bathingsoap Rolling Avg",
        line=dict(dash="dot")
    )
)

fig.update_layout(title="Grouped Bar with Rolling Average Bands")
fig.show()

"""# **اتجاه الربح الكلي للشركة من شهر للتاني.**"""

import plotly.graph_objects as go

profit = df["total_profit"]
months = df["month_number"]

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=months,
        y=profit,
        mode="lines+markers",
        name="Total Profit"
    )
)

fig.add_trace(
    go.Scatter(
        x=months.tolist() + months[::-1].tolist(),
        y=(profit + 5000).tolist() + (profit - 5000)[::-1].tolist(),
        fill="toself",
        fillcolor="rgba(0, 150, 200, 0.1)",
        line=dict(color="rgba(255,255,255,0)"),
        hoverinfo="skip",
        name="Band"
    )
)

fig.update_layout(title="Total Profit with Trend Band")
fig.show()

"""# **حجم مبيعات كل منتج حسب مساحة المربع.**"""

import plotly.express as px

product_columns = ["facecream", "facewash", "toothpaste", "bathingsoap", "shampoo", "moisturizer"]
product_sums = df[product_columns].sum().reset_index()
product_sums.columns = ["product", "sales"]

def band(v):
    if v < 25000: return "Low Band"
    elif v < 45000: return "Medium Band"
    else: return "High Band"

product_sums["band"] = product_sums["sales"].apply(band)

fig = px.treemap(
    product_sums,
    path=["band", "product"],
    values="sales",
    title="Treemap with Sales Bands"
)

fig.show()













